
spring:
  data:
    mongodb:
      uri: mongodb://root:123456@host.docker.internal:27017/notification?authSource=admin&ssl=false
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup, orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:by.lobanovs.notification.dto.order.OrderConfirmation,paymentConfirmation:by.lobanovs.notification.dto.payment.PaymentConfirmation
  mail:
    host: localhost
    port: 1025
    username: lobanovs
    password: lobanovs
    properties:
      mail:
        smtp:
          trust: '*'
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
server:
  port: 8040
